### ISSUE TITLE
ActiveTest failed

### ISSUE THREAD

**Issue by StepDreamSeeker** [bigwhite/gocmpp#14]
Because the submit package and the active test package use same connection, when the submit package is not processed properly, the connection will be disconnected. I think the following changes should be made:
```
// old
if _, ok := r.Packet.Packer.(*CmppActiveTestRspPkt); ok {
	atomic.AddInt32(&c.counter, -1)
	return nil
}
// new
c.counter = 0
```

**Comment by bigwhite** [comment]
Your suggestion is absolutely right if we folllow the cmpp specification strictly. But in practice, we always ignore the submit associated packets when dealing with the counter for active test. This will make the process logic much more simpler.
