### ISSUE TITLE
怎么推送Deliver(状态报告和回复)

### ISSUE THREAD

**Issue by icc99** [bigwhite/gocmpp#15]
err := cmpp.ListenAndServe(":8888",
		cmpp.V30,
		5*time.Second,
		3,
		nil,
		handlers...,
	)
看server.go, 这里只能响应客户的请求. 如果我要主动推送Deliver(状态和回复) 这个要怎么做?
怎么获取这个连接

**Comment by bigwhite** [comment]
这个server.go并非是一个全功能的cmpp3 server，仅支持接收submit消息，并回复应答。
