### ISSUE TITLE
看client.go的例子，在submit SendReq的时候SendReqPkt没有返回SeqId

### ISSUE THREAD

**Issue by JoeCao** [bigwhite/gocmpp#3]
网络乱序的时候，是否会导致无法准确匹配submit提交的结果？

**Comment by bigwhite** [comment]
不是很理解你所说的网络乱序指的是什么？big endian /little endian？

**Comment by JoeCao** [comment]
是这个样子的，根据CMPP3.0的文档
Submit/Submit Resp 为异步传输，发送时填写了序列号"SeqID"，但是"MsgId"这个字段需要网关生成并返回。
而在异步Resp消息体中，规范中要求“SP根据请求和应答消息的Sequence_Id一致性就可得到CMPP_Submit消息的Msg_Id”
这说明我在发送submit之前，必须缓存SeqId到，在返回时通过SeqId匹配到当初发送的那条消息。

不过目前client.go的例子是不缓存SeqId，在submit发送后，立即进入recieve状态，但是这里不一定能拿到返回消息，而且即使拿到的也可能是心跳信息，和submit对应不上。

是否考虑在SendReqPkt方法中返回SeqId，以便业务做缓存、匹配处理？
不知道我这样说，是否清楚？

**Comment by bigwhite** [comment]
c.SendReqPkt后，可以通过p.SeqId获取这个SeqId，获取后可以缓存啊。client.go只是最简单的一个例子而已，只是展示usage而已。
